1670/web1/Models/ErrorViewModel.cs
using System;

namespace web1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

1670/web1/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace web1.Controllers
{
    public class DemoController : Controller
    {
        /* Mục đích: render ra file View
        nằm ở đường dẫn Views/Demo/Index.cshtml
        Demo : tên của Controller (class)
        Index : tên của Action (method) */
        [Route("/demo")]
        public IActionResult Index()
        {
            return View();
        }

        //set thành homepage
        [Route("/")]
        public IActionResult ApplicationDevelopment()
        {
            return View();
        }

        public IActionResult Demo()
        {
            //render view mặc định: Views/Demo/Demo.cshtml 
            //return View();
            //return View("~/Views/Demo/Demo.cshtml");

            //render view tùy biến: Views/Home/Demo.csthml
            return View("~/Views/Home/Demo.cshtml");
        }
    }
}

1670/web1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using web1.Models;

namespace web1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

1670/web1/Controllers/NetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;

namespace web1.Controllers
{
    public class NetController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Razor()
        {
            int age = 30;
            double grade = 7.5;
            bool isPassed = true;
            string name = "Greenwich";
            char c = 'a';
            //1. Pass dữ liệu từ Controller sang View bằng ViewBag
            ViewBag.Ten = name;
            ViewBag.City = "Ha Noi";
            ViewBag.Tuoi = age;

            //2. Pass dữ liệu từ Controller sang View bằng ViewData
            ViewData["Diem"] = grade;
            ViewData["Pass"] = isPassed;
            ViewData["KyTu"] = c;
            ViewData["Month"] = "September";
            
            return View();
        }
    }
}

1670/web1/Views/Demo/ApplicationDevelopment.cshtml
<h1>Module Name: Application Development</h1>
<h2>Module code: 1670</h2>
<h3>Technologies: .NET Core, SQL Server</h3>

<a asp-controller="Net" asp-action="Index">Link to .Net page</a>

1670/web1/Views/Demo/Index.cshtml
<h1>Đây là trang Index
    được render từ action Index
    trong DemoController
</h1>
<h2>URL: localhost:port/Demo/Index</h2>

1670/web1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My first website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Greenwich University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Page 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Page 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Net" asp-action="Index">Net Core</a>
                        </li>
                        <li class="nav-item">
                            <a class="text text-success" href="cms.greenwich.edu.vn">CMS</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <img src="https://img.timviecthietke.com/2021/06/kich-thuoc-banner-website-1.png" width="300" height="150"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
             <h5>Copyright by 1670 - Application Development - Fall 2022</h5>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>