1670/webdemo/Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;

namespace webdemo.Models
{
    public enum Grade
    {
        A, B, C, D, E, F
    }
    public class Enrollment
    {
        //primary key (PK)
        public int EnrollmentId { get; set; }
        
        //foreign key (FK)
        public int CourseId { get; set; }

        [Display(Name = "Mã sinh viên")]
        public int StudentId { get; set; }
        
        //data type: enum Grade
        public Grade Grade { get; set; }

        //navigation properties
        public Course Course { get; set; }
        public Student Student { get; set; }
    }
}

1670/webdemo/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using webdemo.Data;
using webdemo.Models;

namespace webdemo.Controllers
{
    public class CourseController : Controller
    {
        private readonly DemoContext context;

        public CourseController(DemoContext demoContext)
        {
            this.context = demoContext;
        }
        
        //SELECT * FROM Course : View All
        public IActionResult Index()
        {
            var courses = context.Courses.ToList();
            return View(courses);
        }

        //SELECT * FROM COURSE WHERE CourseID = id : VIEW BY ID
        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = context.Courses
                .Include(c => c.Enrollments)
                .ThenInclude(e => e.Student)
                .FirstOrDefault(m => m.CourseId == id);
            return View(course);
        }

        public IActionResult Delete (int? id)
        {
            if (id == null)
                return NotFound();
            var course = context.Courses.Find(id);
            context.Courses.Remove(course);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid)
            {
                context.Add(course);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        public IActionResult Edit (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = context.Courses.Find(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost]
        public IActionResult Edit (Course course)
        {
            if (ModelState.IsValid)
            {
                context.Update(course);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }
    }
}

1670/webdemo/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using webdemo.Data;
using webdemo.Models;

namespace webdemo.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly DemoContext context;
        
        public EnrollmentController (DemoContext demoContext)
        {
            this.context = demoContext;
        }
        public IActionResult Index()
        {
            var enrollments = context.Enrollments.ToList();
            return View(enrollments);
        }
        
        public IActionResult Detail(int? id)
        {
            if (id == null)
                return NotFound();
            var course = context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefault(m => m.EnrollmentId == id);
            return View(course);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var enrollment = context.Enrollments.Find(id);
            context.Enrollments.Remove(enrollment);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        //render ra form Create Enrollment cho người dùng nhập liệu
        public IActionResult Create()
        {
            //lấy dữ liệu từ bảng Course và Student để đổ vào form
            //Create Enrollment cho người dùng lựa chọn
            var courses = context.Courses.ToList();
            var students = context.Students.ToList();
            ViewBag.Courses = courses;
            ViewBag.Students = students;
            return View();
        }

        //nhận & validate dữ liệu từ form Create Enrollment
        //sau đó lưu vào DB & redirect về trang Enrollment Index
        [HttpPost]
        public IActionResult Create(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                context.Enrollments.Add(enrollment);
                context.SaveChanges();
                return RedirectToAction("Index");
               // return RedirectToAction(nameof(Index));
            }
            return View(enrollment);
        }
        
        //render ra form Edit Enrollment
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var enrollment = context.Enrollments.Find(id);
            if (enrollment == null) {
                return NotFound();
            }
            var courses = context.Courses.ToList();
            var students = context.Students.ToList();
            ViewBag.Courses = courses;
            ViewBag.Students = students;
            return View(enrollment);
        }

        //xử lý dữ liệu từ form Edit Enrollment
        [HttpPost]
        public IActionResult Edit (Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                context.Enrollments.Update(enrollment);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enrollment);
        }
    }
}

1670/webdemo/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using webdemo.Data;
using webdemo.Models;

namespace webdemo.Controllers
{
    public class StudentController : Controller
    {
        private readonly DemoContext _context;
        public StudentController(DemoContext context)
        {
            _context = context;
        }

        //READ feature: SELECT * FROM Student

        //Method 1: synchronous (đồng bộ) 
        public IActionResult Index()
        {
            var students = _context.Students.ToList();
            var total = _context.Students.ToList().Count();
            //ViewBag.Total = total;
            ViewData["total"] = total;
            return View(students);
        }

        //Method 2: asynchronous (bất đồng bộ) => recommended
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Students.ToListAsync());
        //}

        //READ feature: SELECT * FROM Student WHERE Id = id
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                   .Include(s => s.Enrollments)
                   .ThenInclude(e => e.Course)
                   .FirstOrDefaultAsync(m => m.Id == id);
            return View(student);
        }

        //DELETE FROM Student WHERE Id = id
        public IActionResult Delete (int? id)
        {
            if (id == null)
                return NotFound();
            var student = _context.Students.Find(id);
            _context.Remove(student);
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }

        //CREATE feature: INSERT INTO Student (LastName, FirstMidName, EnrollmentDate) VALUES (?,?,?)
        //tạo hàm để render ra form Create Student
        public IActionResult Create()
        {
            return View(); 
        }

        //tạo hàm để nhận dữ liệu từ form Create Student
        [HttpPost]
        public IActionResult Create(Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        //UPDATE feature: UPDATE Student SET .... WHERE StudentId = id
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = _context.Students.Find(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost]
        public IActionResult Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Update(student);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }
    }
}

1670/webdemo/Views/Enrollment/Create.cshtml
@model webdemo.Models.Enrollment

<div class="container-fluid col-md-5 text-center mt-3">
    <h5 class="alert alert-warning">Create new enrollment</h5>
    <form class="card p-3 bg-light" action="Create" method="post">
        <div class="form-group">
            <label>Course name</label>
            <select class="form-control" asp-for="CourseId" asp-items="@(new SelectList(ViewBag.Courses,"CourseId","Title"))">
                <option>Select a course ...</option>
             </select>
             <span class="text text-danger" asp-validation-for="CourseId"></span>
        </div>
         <div class="form-group">
            <label>Student name</label>
            <select class="form-control" asp-for="StudentId">
            <option>Select a student ...</option>
                @foreach (var student in ViewBag.Students)
                {
                    <option value="@student.Id">@student.FirstMidName @student.LastName</option>
                }
             </select>
             <span class="text text-danger" asp-validation-for="StudentId"></span>
        </div>
        <div class="form-group">
            <label asp-for="Grade"></label>
            <select class="form-control" asp-for="Grade" asp-items="Html.GetEnumSelectList<Grade>()">
                <option>Select a grade ...</option>
            </select>
            <span class="text text-danger" asp-validation-for="Grade"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Create">
        </div>
    </form>
</div>

1670/webdemo/Views/Enrollment/Detail.cshtml
@model webdemo.Models.Enrollment;

<div class="container col-md-10 text-center mt-3">
    <table class="table table-hover mt-3">
        <tr>
            <th colspan="2" class="text text-warning">
                <h3>Enrollment Detail</h3>
            </th>
        </tr>
        <tr>
            <th>
                Student Name
            </th>
            <td>
                <a asp-controller="Student" asp-action="Detail" asp-route-id="@Model.StudentId">
                     @Model.Student.FirstMidName @Model.Student.LastName
                </a> 
            </td>
        </tr>
        <tr>
            <th>
                Course Title
            </th>
            <td>
                <a asp-controller="Course" asp-action="Detail" asp-route-id="@Model.CourseId">
                     @Model.Course.Title
                </a>  
            </td>
        </tr>
        <tr>
        <tr>
            <th>
                Student Grade
            </th>
            <td>
                @Model.Grade
            </td>
        </tr>
    </table>  
</div>

1670/webdemo/Views/Enrollment/Edit.cshtml
@model webdemo.Models.Enrollment

<div class="container-fluid col-md-5 text-center mt-3">
    <h5 class="alert alert-warning">Edit enrollment</h5>
    <form class="card p-3 bg-light" action="Edit" method="post">
        <input type="hidden" asp-for="EnrollmentId" />
        <div class="form-group">
            <label>Course name</label>
            <select class="form-control" asp-for="CourseId" asp-items="@(new SelectList(ViewBag.Courses,"CourseId","Title"))">
                <option>Select a course ...</option>
             </select>
             <span class="text text-danger" asp-validation-for="CourseId"></span>
        </div>
         <div class="form-group">
            <label>Student name</label>
            <select class="form-control" asp-for="StudentId">
            <option>Select a student ...</option>
                @foreach (var student in ViewBag.Students)
                {
                    <option value="@student.Id">@student.FirstMidName @student.LastName</option>
                }
             </select>
             <span class="text text-danger" asp-validation-for="StudentId"></span>
        </div>
        <div class="form-group">
            <label asp-for="Grade"></label>
            <select class="form-control" asp-for="Grade" asp-items="Html.GetEnumSelectList<Grade>()">
                <option>Select a grade ...</option>
            </select>
            <span class="text text-danger" asp-validation-for="Grade"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Edit">
        </div>
    </form>
</div>

1670/webdemo/Views/Enrollment/Index.cshtml
@model ICollection<webdemo.Models.Enrollment>

<div class="container col-md-8 text-center mt-3">
    <h1 class="text text-primary">Enrollment List</h1>
    <a asp-action="Create">
        <img src="~/images/add.png" width="50" height="40" />
    </a>
    <table class="table table-bordered mt-4">
        <thead>
            <tr>
                <th>
                    Enrollment Id
                </th>
                 <th>
                    Student Name
                </th>
                 <th>
                    Course Name
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var enrollment in Model)
           {
               <tr>
                   <td>
                       @Html.DisplayFor(item => enrollment.EnrollmentId)
                   </td>
                    <td>
                       @Html.DisplayFor(item => enrollment.StudentId)
                   </td>
                   <td>
                       @Html.DisplayFor(item => enrollment.CourseId)
                   </td>
                   <td>
                           <a asp-controller="Enrollment" asp-action="Detail" asp-route-id="@enrollment.EnrollmentId">
                                <img src="~/images/detail.jpg" width="50" height="40" />
                           </a>
                           <a asp-controller="Enrollment" asp-action="Edit" asp-route-id="@enrollment.EnrollmentId">
                                <img src="~/images/edit.jpg" width="50" height="40" />
                           </a>
                           <a asp-controller="Enrollment" asp-action="Delete" asp-route-id="@enrollment.EnrollmentId"
                           onclick="return confirm('Are you sure to delete this enrollment ?')"
                           >
                                <img src="~/images/delete.jpg" width="50" height="40" />
                           </a>
                   </td>
               </tr>
           }
        </tbody>
    </table>
</div>