1670/demo/Models/University.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace demo.Models
{
    //relationship: University - Student : One - Many
    public class University
    {
        public int Id { get; set; } //Primary key

        [Required]
        [Display(Name = "University Name")]
        public string Name { get; set; }

        public string Address { get; set; }

        [Required]
        public string Logo { get; set; }

        //khai báo ICollection để kết nối đến Student từ University
        public ICollection<Student> Students { get; set; }
    }
}

1670/demo/Controllers/StudentController.cs
using demo.Data;
using demo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace demo.Controllers
{
    public class StudentController : Controller
    {
        //attribute
        private readonly ApplicationDbContext context;

        //constructor (auto-generate : Alt+Enter => Generate constructor)
        public StudentController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [Route("/")]
        public IActionResult Index()
        {
            return View(context.Students.ToList());
        }

        public IActionResult List()
        {
            return View(context.Students.ToList());
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                //nếu id không tìm thấy thì trả về not found
                return NotFound();
            }
            else
            {
                //tìm ra object student có id được yêu cầu
                var student = context.Students.Find(id);
                //xóa object student vừa tìm thấy
                context.Students.Remove(student);
                //lưu lại thay đổi trong db
                context.SaveChanges();

                //gửi thông báo về trang Index
                //bắt buộc dùng TempData để có thể gửi dữ liệu về View nếu return RedirectToAction
                TempData["Message"] = "Delete student successfully !";

                //quay trở lại trang index sau khi thành công
                //return RedirectToAction("Index");
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Detail(int id)
        {
            var student = context.Students
                                 .Include(s => s.University)
                                 .FirstOrDefault(s => s.Id == id);
            return View(student);
        }

        [HttpGet]
        public IActionResult Add ()
        {
            //lấy ra dữ liệu từ bảng University và lưu vào list
            var universities = context.Universities.ToList();
            //dữ liệu đẩy vào ViewBag để gọi đến trong View
            ViewBag.Universities = universities;
            return View();
        }

        [HttpPost]
        public IActionResult Add(Student student)
        {
            //nếu người dùng nhập đủ và đúng thông tin vào form
            //thì dữ liệu sẽ được add vào database
            if (ModelState.IsValid)
            {
                context.Students.Add(student);
                context.SaveChanges();
                TempData["Message"] = "Add student successfully !";
                return RedirectToAction("index");
            }
            else  
            //ngược lại nếu người dùng nhập sai thì quay ngược trở lại form để add
            //Lưu ý: cần tạo và giá trị cho biến ViewBag => tránh bị lỗi object null
            {
                ViewBag.Universities = context.Universities.ToList();
                return View(student);
            }
        }

        [HttpGet]
        public IActionResult Edit (int id)
        {
            //lấy ra dữ liệu từ bảng University và lưu vào list
            var universities = context.Universities.ToList();
            //dữ liệu đẩy vào ViewBag để gọi đến trong View
            ViewBag.Universities = universities;
            return View(context.Students.Find(id));
        }

        [HttpPost]
        public IActionResult Edit (Student student)
        {
            if (ModelState.IsValid)
            {
                context.Students.Update(student);
                context.SaveChanges();
                TempData["Message"] = "Edit student successfully !";
                return RedirectToAction("index");
            }
            else
            {
                ViewBag.Universities = context.Universities.ToList();
                return View(student);
            }
        }

        public IActionResult SortNameAsc ()
        {
            return View("Index",context.Students.OrderBy(s => s.Name).ToList());
        }

        public IActionResult SortNameDesc ()
        {
            return View("Index",context.Students.OrderByDescending(s => s.Name).ToList());
        }

        [HttpPost]
        public IActionResult Search (string keyword)
        {
            var students = context.Students.Where(s => s.Name.Contains(keyword)).ToList();
            if (students.Count == 0)
            {
                TempData["Message"] = "No student found";
            }
            return View("Index", students);
        }
    }
}

1670/demo/Controllers/UniversityController.cs
using demo.Data;
using demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net.Mime;

namespace demo.Controllers
{
    public class UniversityController : Controller
    {
        private readonly ApplicationDbContext context;

        public UniversityController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            //trả về list theo thứ tự ID tăng dần (cũ ở đầu, mới ở cuối danh sách)
            //var universities = context.Universities.ToList();

            //trả về list theo ID giảm dần (cái mới sẽ được hiển thị ở đầu thay vì cuối)
            var universities = context.Universities.OrderByDescending(university => university.Id).ToList();
            return View(universities);
        }

        public IActionResult Info(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var university = context.Universities
                                    .Include(u => u.Students)
                                    .FirstOrDefault(u => u.Id == id);
            //Note: khi muốn truy xuất dữ liệu của bảng B từ bảng A
            //thì cần sử dụng Include kết hợp với FirstOrDefault
            //còn nếu chỉ truy xuất thông tin id đơn thuần thì sử dụng
            //Find hoặc FirstOrDefault đều được
            return View(university);
        }

        public IActionResult Remove (int id)
        {
            var university = context.Universities.Find(id);
            context.Universities.Remove(university);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add ()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add (University university)
        {
            //kiểm tra thông tin nhập vào từ form
            if (ModelState.IsValid)
            {
                //nếu hợp lệ thì add vào db
                context.Universities.Add(university);
                //lưu thay đổi vào db
                context.SaveChanges();
                //return về trang index
                return RedirectToAction("Index");
                //return RedirectToAction(nameof(Index));
            }
            //nếu không hợp lệ thì quay ngược về form 
            return View(university);
        }

        [HttpGet]
        public IActionResult Edit (int id)
        {
            var university = context.Universities.Find(id);
            return View(university);
        }

        [HttpPost]
        public IActionResult Edit (University university)
        {
            //kiểm tra thông tin nhập vào từ form
            if (ModelState.IsValid)
            {
                //nếu hợp lệ thì cập nhật vào db
                context.Universities.Update(university);
                //lưu thay đổi vào db
                context.SaveChanges();
                //return về trang index
                return RedirectToAction("Index");
                //return RedirectToAction(nameof(Index));
            }
            //nếu không hợp lệ thì quay ngược về form 
            return View(university);
        }
    }
}

1670/demo/Views/University/Add.cshtml
@model demo.Models.University

<form class="card p-3 bg-light" method="post" asp-controller="University" asp-action="Add">
    <h4 class="text text-success">Add new university</h4>
    <div class="form-group">
        <label class="h6 text-primary" asp-for="@Model.Name"></label>
        <input class="form-control" asp-for="@Model.Name" />
        <span class="text-danger" asp-validation-for="@Model.Name"></span>
    </div>
    <div class="form-group">
        <label class="h6 text-primary" asp-for="@Model.Address"></label>
        <input class="form-control" asp-for="@Model.Address" />
        <span class="text-danger" asp-validation-for="@Model.Address"></span>
    </div>
    <div class="form-group">
        <label class="h6 text-primary">University Image</label>
        <input class="form-control" asp-for="@Model.Logo" />
        <span class="text-danger" asp-validation-for="@Model.Logo"></span>
    </div>
    <div class="form-group">
        <input class="btn btn-warning" type="submit" value="Add" />
    </div>
</form>

1670/demo/Views/University/Edit.cshtml
@model demo.Models.University

<form class="card p-3 bg-light" method="post" asp-controller="University" asp-action="Edit">
    <h4 class="text text-success">Edit university</h4>
    <div class="form-group">
        <label class="h6 text-primary" asp-for="@Model.Name"></label>
        <input class="form-control" asp-for="@Model.Name" />
        <span class="text-danger" asp-validation-for="@Model.Name"></span>
    </div>
    <div class="form-group">
        <label class="h6 text-primary" asp-for="@Model.Address"></label>
        <input class="form-control" asp-for="@Model.Address" />
        <span class="text-danger" asp-validation-for="@Model.Address"></span>
    </div>
    <div class="form-group">
        <label class="h6 text-primary">University Image</label><br />
        <img src="@Model.Logo" width="80" height="80" /><br />
        <input class="form-control mt-3" asp-for="@Model.Logo" />
        <span class="text-danger" asp-validation-for="@Model.Logo"></span>
    </div>
    <div class="form-group">
        <input class="btn btn-warning" type="submit" value="Edit" />
    </div>
</form>

1670/demo/Views/University/Index.cshtml
@model List<University>

<table class="table table-info">
    <tr>
        <th colspan="4">University List</th>
        <th>
            <a class="btn btn-primary" asp-controller="University" asp-action="Add">Add</a>
        </th>
    </tr>
    <tr>
        <th>University Id</th>
        <th>University Name</th>
        <th>University Address</th>
        <th>University Logo</th>
        <th>Menu</th>
    </tr>
    @foreach (var uni in Model)
   {
       <tr>
           <td>@uni.Id</td>
           <td>@uni.Name</td>
           <td>@uni.Address</td>
           <td>
               <a asp-controller="University" asp-action="Info" asp-route-id="@uni.Id">
                <img src="@uni.Logo" 
                width="100" height="100" />
                </a>
            </td>
           <td>
               <a asp-controller="University" asp-action="Edit" class="btn btn-warning"
                  asp-route-id="@uni.Id">Edit</a>
               <a asp-controller="University" asp-action="Remove" class="btn btn-danger"
                  asp-route-id="@uni.Id" onclick="return confirm('Are you sure to remove this university ?');">Remove</a>
           </td>
       </tr>
   }
</table>

1670/demo/Views/University/Info.cshtml
@model demo.Models.University

<div class="container text-center">
    <div class="row">
        <div class="col">
            <img src="@Model.Logo" width="300" height="300" />
            <h2 class="text text-success mt-3">@Model.Name</h2>
        </div>
        <div class="col">
            <table class="table table-bordered">
                <tr>
                    <th colspan="2">Student List</th>
                    <th>TOTAL: @Model.Students.Count</th>
                </tr>
                <tr>
                    <th>Student Id</th>
                    <th>Student Name</th>
                    <th>Student Avatar</th>
                </tr>
                @foreach (var student in Model.Students)
                {
                    <tr>
                        <td>@student.SId</td>
                        <td>@student.Name</td>
                        <td>
                            <a asp-controller="Student" asp-action="Detail" asp-route-id="@student.Id">
                                <img src="@student.Image" width="80" height="80">
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>